global:
  storageClass: &default-storage-class "standard"
  ## @param global.defaultVectorStoreType Defines the default vector database type, currently `chroma` and `pgvector` are available
  ## When the option is `chroma`, it needs `chromadb.enabled` to be `true` as well to work.
  ## When the option is `pgvector`, it needs `postgresql.enabled` to be `true` as well to work.
  defaultVectorStoreType: pgvector

  # Enable and update the ip if nip.io is NOT accessible in deployed environment
  hostConfig:
    enabled: true
    hostAliases:
      - hostnames:
          - portal.<replaced-ingress-nginx-ip>.nip.io
          - gpts.<replaced-ingress-nginx-ip>.nip.io
          - minio-api.<replaced-ingress-nginx-ip>.nip.io
          - fastchat-api.<replaced-ingress-nginx-ip>.nip.io
          - fastchat-controller.<replaced-ingress-nginx-ip>.nip.io
          - minio-api.<replaced-ingress-nginx-ip>.nip.io
          - postgresql.<replaced-ingress-nginx-ip>.nip.io
        ip: <replaced-ingress-nginx-ip>

# @section config is used to configure the system
config:
  # embedder is used as the system default embedding service
  embedder:
    enabled: false
    model: "bge-large-zh-v1.5"
  # rerank is the default model for reranking service
  rerank:
    enabled: true
    model: "bge-reranker-large"

# @section controller is used as the core controller for arcadia
# @param image Image to be used
# @param imagePullPolcy ImagePullPolicy
# @param resources Resources to be used
controller:
  # 1: error 3: info  5: debug 
  loglevel: 3
  image: kubeagi/arcadia:v0.2.1-20240329-f4655d3
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 64Mi

# @section graphql and bff server
# related project: https://github.com/kubeagi/arcadia/tree/main/apiserver
apiserver:
  loglevel: 3
  image: kubeagi/arcadia:v0.2.1-20240329-f4655d3
  enableplayground: false
  port: 8081
  ingress:
    enabled: true
    path: kubeagi-apis
    host: portal.<replaced-ingress-nginx-ip>.nip.io
    proxyBodySize: 100m
  oidc:
    enabled: true
    clientID: bff-client
    clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
    issuerURL: https://portal.<replaced-ingress-nginx-ip>.nip.io/oidc
    masterURL: https://k8s.<replaced-ingress-nginx-ip>.nip.io

# @section portal for arcadia operation console
opsconsole:
  enabled: true
  kubebbEnabled: true
  image: kubeagi/ops-console:v0.2.1-20240329-87ae2e0
  ingress:
    path: kubeagi-portal-public
    host: portal.<replaced-ingress-nginx-ip>.nip.io

# @section configurations for GPT Store
gpts:
  enabled: true
  # all gpt resources are public in this namespace
  public_namespace: gpts
  agentportal:
    image: kubeagi/agent-portal:v0.1.0-20240329-cc3d5f4
    ingress:
      path: ""
      host: gpts.<replaced-ingress-nginx-ip>.nip.io

# @section fastchat is used as fastchat configurations for arcadia
fastchat:
  enabled: true
  image:
    repository: kubeagi/arcadia-fastchat
    tag: v0.2.36
  ingress:
    enabled: true
    host: fastchat-api.<replaced-ingress-nginx-ip>.nip.io

# @section minio is used as default Object-Storage-Service for arcadia
minio:
  image:
    repository: kubeagi/minio
    tag: RELEASE.2023-02-10T18-48-39Z
  mode: standalone
  rootUser: "admin"
  rootPassword: "Passw0rd!"
  persistence:
    enabled: true
    storageClass: *default-storage-class
    size: 30Gi
  ingress:
    enabled: true
    proxyBodySize: 10240m
    api:
      enabled: true
      insecure: false
      port: 9000
      host: minio-api.<replaced-ingress-nginx-ip>.nip.io
    console:
      enabled: true
      port: 9001
      host: minio-console.<replaced-ingress-nginx-ip>.nip.io
    cert:
      ipAddresses:
      - <replaced-ingress-nginx-ip>
      dnsNames:
      - minio-api.<replaced-ingress-nginx-ip>.nip.io
      - minio-console.<replaced-ingress-nginx-ip>.nip.io

# @section dataprocess is used to configure data processing service
# Related project: https://github.com/kubeagi/arcadia/tree/main/data-processing
dataprocess:
  enabled: true
  image: kubeagi/data-processing:v0.2.1
  port: 28888
  config:
    llm:
      qa_retry_count: '2'
    worker: 1
    chunkSize: 500

# @section postgresql is used to configure postgresql service
# Posgresql service will be used in two parts:
# - dataprocessing
# - llm application
# - used as vector store with pgvector enabled(Recommended)
postgresql:
  enabled: true
  global:
    storageClass: *default-storage-class
    postgresql:
      auth:
        # default username and password
        username: "admin"
        password: "Passw0rd!"
        # default database
        database: "arcadia"
  # image configurations
  image:
    registry: docker.io
    repository: kubeagi/postgresql
    tag: 16.1.0-debian-11-r18-pgvector-v0.5.1
    pullPolicy: IfNotPresent
  primary:
    initdb:
      scriptsConfigMap: pg-init-data

# @section chromadb is used to deploy a chromadb instance
chromadb:
  enabled: false
  image:
    repository: kubeagi/chromadb
  chromadb:
    apiVersion: "0.4.18"
    auth:
      enabled: false
    serverHttpPort: 8000
    dataVolumeStorageClass: *default-storage-class
    dataVolumeSize: "1Gi"

# @section ray is a unified framework for scaling AI and Python applications.In kubeagi,we use ray for distributed inference
ray:
  # clusters provided by ray
  # For more information on cluster configurations,please refer to http://kubeagi.k8s.com.cn/docs/Configuration/DistributedInference/run-inference-using-ray
  clusters: {}
    # # cluster1 comes from https://github.com/kubeagi/arcadia/blob/main/config/samples/ray.io_v1_raycluster.yaml
    # - name: cluster1
    #   headAddress: raycluster-kuberay-head-svc.kuberay-system.svc:6379
    #   pythonVersion: 3.9.18
    #   dashboardHost: raycluster-kuberay-head-svc.kuberay-system.svc:8265