global:
  oss:
    bucket: &default-oss-bucket "arcadia"
# @section deployment is used as default deployment configurations for arcadia
# @param image Image to be used
# @param imagePullPolcy ImagePullPolicy
# @param resources Resources to be used
deployment:
  image: kubeagi/arcadia:v0.1.0
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      cpu: "1"
      memory: 1024Mi
    requests:
      cpu: 10m
      memory: 64Mi

# @section fastchat is used as fastchat configurations for arcadia
fastchat:
  ingress:
    enabled: false
    className: portal-ingress
    hosts:
      - host: fastchat-api.fastchat.arcadia.com
        paths:
          - path: /
            port: 8000
            pathType: ImplementationSpecific
      - host: fastchat-controller.fastchat.arcadia.com
        paths:
          - path: /
            port: 21001
            pathType: ImplementationSpecific


# @section oss is used as default Object-Storage-Service for arcadia which provides the capability to
# - host user-uploaded data files as local datasource
# - host user-uploaded models
# The following params comes from kubeagi/minio in repository https://kubebb.github.io/components
# @param oss.enabled Enable Object-Storage-Service in arcadia
# @param oss.buckets List of default buckets in arcadia
minio:
  mode: standalone
  rootUser: "admin"
  rootPassword: "Passw0rd!"
  persistence:
    enabled: true
    storageClass: ""
    size: 30Gi
  buckets:
    # Name of the bucket
    - name: *default-oss-bucket
      # Policy to be set on the
      # bucket [none|download|upload|public|custom]
      # if set to custom, customPolicy must be set.
      policy: "none"
      # set versioning for
      # bucket [true|false]
      versioning: false
      # set objectlocking for
      # bucket [true|false] NOTE: versioning is enabled by default if you use locking
      objectlocking: false

portal:
  enabled: false
  port: 8081
  ingress:
    path: ""
    enabled: false
    host: portal.172.22.96.167.nip.io
  enableplayground: false
  dataProcessURL: http://arcadia-dataprocess.svc.cluster.local:28888
  oidc:
    enabled: false
    clientID: bff-client
    issuerURL: https://portal.172.22.96.167.nip.io/oidc
    clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
    masterURL: https://k8s.172.22.96.167.nip.io

vectorstore:
  url: http://chroma-chromadb.arcadia.svc:8000
  chroma:
    distanceFunction: cosine

dataprocess:
  enabled: false
  repository: kubeagi/data-processing
  tag: v0.1.0
  port: 28888
  env:
    minio:
      accessKey: os4GDEmSZaJwweoj
      secretKey: ROVfENZuyUtpRNOT4mtTQicA3CPASQ89
      apiURL: https://kubeagi-minio.172.22.96.136.nip.io
      secure: false
    zhipu:
      key: zhipu
      knowledge:
        chunkSize: 500
        chunkOverlap: 50
    postgres:
      host: 172.22.96.136
      port: 30030
      user: admin
      password: Passw0rd!
      database: arcadia
