definitions:
  chat.APPMetadata:
    properties:
      app_name:
        description: AppName, the name of the application
        example: chat-with-llm
        type: string
      app_namespace:
        description: AppNamespace, the namespace of the application
        example: arcadia
        type: string
    required:
    - app_name
    - app_namespace
    type: object
  chat.ChatReqBody:
    properties:
      app_name:
        description: AppName, the name of the application
        example: chat-with-llm
        type: string
      app_namespace:
        description: AppNamespace, the namespace of the application
        example: arcadia
        type: string
      conversation_id:
        description: ConversationID, if it is empty, a new conversation will be created
        example: 5a41f3ca-763b-41ec-91c3-4bbbb00736d0
        type: string
      query:
        description: Query user query string
        example: 旷工最小计算单位为多少天？
        type: string
      response_mode:
        allOf:
        - $ref: '#/definitions/chat.ResponseMode'
        description: |-
          ResponseMode:
          * Blocking - means the response is returned in a blocking manner
          * Streaming - means the response will use Server-Sent Events
        example: blocking
    required:
    - app_name
    - app_namespace
    - query
    - response_mode
    type: object
  chat.ChatRespBody:
    properties:
      conversation_id:
        example: 5a41f3ca-763b-41ec-91c3-4bbbb00736d0
        type: string
      created_at:
        description: CreatedAt is the time when the message is created
        example: "2023-12-21T10:21:06.389359092+08:00"
        type: string
      message:
        description: Message is what AI say
        example: 旷工最小计算单位为0.5天。
        type: string
      message_id:
        example: 4f3546dd-5404-4bf8-a3bc-4fa3f9a7ba24
        type: string
      references:
        description: References is the list of references
        items:
          $ref: '#/definitions/retriever.Reference'
        type: array
    type: object
  chat.Conversation:
    properties:
      app_name:
        example: chat-with-llm
        type: string
      app_namespace:
        example: arcadia
        type: string
      id:
        example: 5a41f3ca-763b-41ec-91c3-4bbbb00736d0
        type: string
      messages:
        items:
          $ref: '#/definitions/chat.Message'
        type: array
      started_at:
        example: "2023-12-21T10:21:06.389359092+08:00"
        type: string
      updated_at:
        example: "2023-12-22T10:21:06.389359092+08:00"
        type: string
    type: object
  chat.ConversationReqBody:
    properties:
      app_name:
        description: AppName, the name of the application
        example: chat-with-llm
        type: string
      app_namespace:
        description: AppNamespace, the namespace of the application
        example: arcadia
        type: string
      conversation_id:
        description: ConversationID, if it is empty, a new conversation will be created
        example: 5a41f3ca-763b-41ec-91c3-4bbbb00736d0
        type: string
    required:
    - app_name
    - app_namespace
    type: object
  chat.ErrorResp:
    properties:
      error:
        example: conversation is not found
        type: string
    type: object
  chat.Message:
    properties:
      answer:
        example: 旷工最小计算单位为0.5天。
        type: string
      id:
        example: 4f3546dd-5404-4bf8-a3bc-4fa3f9a7ba24
        type: string
      query:
        example: 旷工最小计算单位为多少天？
        type: string
      references:
        items:
          $ref: '#/definitions/retriever.Reference'
        type: array
    type: object
  chat.MessageReqBody:
    properties:
      app_name:
        description: AppName, the name of the application
        example: chat-with-llm
        type: string
      app_namespace:
        description: AppNamespace, the namespace of the application
        example: arcadia
        type: string
      conversation_id:
        description: ConversationID, if it is empty, a new conversation will be created
        example: 5a41f3ca-763b-41ec-91c3-4bbbb00736d0
        type: string
      message_id:
        description: MessageID, single message id
        example: 4f3546dd-5404-4bf8-a3bc-4fa3f9a7ba24
        type: string
    required:
    - app_name
    - app_namespace
    type: object
  chat.ResponseMode:
    enum:
    - blocking
    - streaming
    type: string
    x-enum-varnames:
    - Blocking
    - Streaming
  chat.SimpleResp:
    properties:
      message:
        example: ok
        type: string
    type: object
  retriever.Reference:
    properties:
      answer:
        description: Answer row
        example: 旷工最小计算单位为 0.5 天。
        type: string
      file_path:
        description: file fullpath
        example: dataset/dataset-playground/v1/qa.csv
        type: string
      line_number:
        description: line number in the file
        example: 7
        type: integer
      question:
        description: Question row
        example: 'q: 旷工最小计算单位为多少天？'
        type: string
      score:
        description: vector search score
        example: 0.34
        type: number
    type: object
info:
  contact: {}
paths:
  /:
    post:
      consumes:
      - application/json
      description: chat with application
      parameters:
      - description: Should the chat request be treated as debugging?
        in: query
        name: debug
        type: boolean
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat.ChatReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: blocking mode, will return all field; streaming mode, only
            conversation_id, message and created_at will be returned
          schema:
            $ref: '#/definitions/chat.ChatRespBody'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/chat.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/chat.ErrorResp'
      summary: chat with application
      tags:
      - application
  /conversations:
    post:
      consumes:
      - application/json
      description: list all conversations
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat.APPMetadata'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/chat.Conversation'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/chat.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/chat.ErrorResp'
      summary: list all conversations
      tags:
      - application
  /conversations/:conversationID:
    delete:
      consumes:
      - application/json
      description: delete one conversation
      parameters:
      - description: conversationID
        in: path
        name: conversationID
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/chat.SimpleResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/chat.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/chat.ErrorResp'
      summary: delete one conversation
      tags:
      - application
  /messages:
    post:
      consumes:
      - application/json
      description: get all messages history for one conversation
      parameters:
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat.ConversationReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/chat.Conversation'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/chat.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/chat.ErrorResp'
      summary: get all messages history for one conversation
      tags:
      - application
  /messages/:messageID/references:
    post:
      consumes:
      - application/json
      description: get one message's references
      parameters:
      - description: messageID
        in: path
        name: messageID
        required: true
        type: string
      - description: query params
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/chat.MessageReqBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/retriever.Reference'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/chat.ErrorResp'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/chat.ErrorResp'
      summary: get one message references
      tags:
      - application
swagger: "2.0"
