apiVersion: v1
data:
  config: |
    systemDatasource:
      apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
      kind: Datasource
      name: '{{ .Release.Name }}-minio'
      namespace: '{{ .Release.Namespace }}'
    gateway:
      apiServer: 'http://{{ .Release.Name }}-fastchat.{{ .Release.Namespace }}.svc.cluster.local:8000'
      controller: 'http://{{ .Release.Name }}-fastchat.{{ .Release.Namespace }}.svc.cluster.local:21001'
    vectorStore:
      apiGroup: arcadia.kubeagi.k8s.com.cn/v1alpha1
      kind: VectorStore
      name: '{{ .Release.Name }}-vectorstore'
      namespace: '{{ .Release.Namespace }}'
kind: ConfigMap
metadata:
  labels:
    control-plane: {{ .Release.Name }}-arcadia
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}