apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Datasource
metadata:
  name:  {{ .Release.Name }}-minio
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
spec:
  displayName: "内置系统数据源"
  description: "Arcadia 内置系统数据源"
  endpoint:
    url: {{ .Values.minio.ingress.api.host }}
    internalURL: {{ .Release.Name }}-minio.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.minio.ingress.api.port }}
    authSecret:
      kind: Secret
      name: {{ .Release.Name }}-minio
    insecure: {{ .Values.minio.ingress.api.insecure }}
  oss:
    # pre-defined buckets for arcadia
    bucket: {{ .Values.global.oss.bucket }}
