minio:
  access_key: '${MINIO_ACCESSKEY: hpU4SCmj5jiU7IP5}'
  secret_key: '${MINIO_SECRETKEY: 7AUewBESqvKijdnNskm8nU6emTZ3rG8F}'
  api_url: '${MINIO_API_URL: kubeagi-minio.172.22.96.136.nip.io}'
  secure: '${MINIO_SECURE: True}'
  dataset_prefix: '${MINIO_DATASET_PREFIX: dataset}'

zhipuai:
  api_key: '${ZHIPUAI_API_KEY: 871772ac03fcb9db9d4ce7b1e6eea210.VZZVy0mCox0WrzQI}'

llm:
  use_type: '${LLM_USE_TYPE: open_ai}' # zhi_pu_online or open_ai
  qa_retry_count: '${LLM_QA_RETRY_COUNT: 100}'

open_ai:
  key: '${OPEN_AI_DEFAULT_KEY: fake}'
  base_url: '${OPEN_AI_DEFAULT_BASE_URL: http://arcadia-fastchat.172.22.96.167.nip.io/v1}'
  model: '${OPEN_AI_DEFAULT_MODEL_NAME: 3d407a8b-90ab-43c4-9fc0-87e533368570}'



knowledge:
  chunk_size: '${KNOWLEDGE_CHUNK_SIZE: 500}'
  chunk_overlap: '${KNOWLEDGE_CHUNK_OVERLAP: 50}'

backendPg:
  host: '${PG_HOST: localhost}'
  port: '${PG_PORT: 5432}'
  user: '${PG_USER: postgres}'
  password: '${PG_PASSWORD: 123456}'
  database: '${PG_DATABASE: data_process}'


  


