# permissions for end users to edit apichains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apichain-editor-role
rules:
- apiGroups:
  - chain.kubeagi.k8s.com.cn
  resources:
  - apichains
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - chain.kubeagi.k8s.com.cn
  resources:
  - apichains/status
  verbs:
  - get
