# permissions for end users to view apichains.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apichain-viewer-role
rules:
- apiGroups:
  - chain.kubeagi.k8s.com.cn
  resources:
  - apichains
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - chain.kubeagi.k8s.com.cn
  resources:
  - apichains/status
  verbs:
  - get
