# permissions for end users to edit laboratories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laboratory-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/status
  verbs:
  - get
