# permissions for end users to view laboratories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: laboratory-viewer-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - laboratories/status
  verbs:
  - get
