# permissions for end users to view versioneddatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: versioneddataset-viewer-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/status
  verbs:
  - get
