# permissions for end users to edit versioneddatasets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: versioneddataset-editor-role
rules:
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - arcadia.kubeagi.k8s.com.cn
  resources:
  - versioneddatasets/status
  verbs:
  - get
