deployment:
  image: kubebb/arcadia:v0.0.0-20230822-1b9f847
  imagePullPolcy: IfNotPresent
  resources:
    limits:
      cpu: 5000m
      memory: 1280Mi
    requests:
      cpu: 10m
      memory: 64Mi
