global:
  oss:
    bucket: &default-oss-bucket "arcadia"
# @section deployment is used as default deployment configurations for arcadia
# @param image Image to be used
# @param imagePullPolcy ImagePullPolicy
# @param resources Resources to be used
deployment:
  image: kubebb/arcadia:v0.0.1
  imagePullPolcy: IfNotPresent
  resources:
    limits:
      cpu: 5000m
      memory: 1280Mi
    requests:
      cpu: 10m
      memory: 64Mi

# @section fastchat is used as fastchat configurations for arcadia
fastchat:
  ingress:
    enabled: false
    className: portal-ingress
    hosts:
      - host: fastchat-api.fastchat.arcadia.com
        paths:
          - path: /
            port: 8000
            pathType: ImplementationSpecific
      - host: fastchat-controller.fastchat.arcadia.com
        paths:
          - path: /
            port: 21001
            pathType: ImplementationSpecific


# @section oss is used as default Object-Storage-Service for arcadia which provides the capability to
# - host user-uploaded data files as local datasource
# - host user-uploaded models
# The following params comes from kubebb/minio in repository https://kubebb.github.io/components
# @param oss.enabled Enable Object-Storage-Service in arcadia
# @param oss.buckets List of default buckets in arcadia
minio:
  mode: standalone
  rootUser: "admin"
  rootPassword: "Passw0rd!"
  persistence:
    enabled: true
    storageClass: ""
    size: 30Gi
  users:
    - accessKey: q18aRFqWOAX7pEin
      secretKey: nCbZIP6q4s8KtQpL7n8CD2N88H6XABGf
      policy: readwrite
  buckets:
    # Name of the bucket
    - name: *default-oss-bucket
      # Policy to be set on the
      # bucket [none|download|upload|public|custom]
      # if set to custom, customPolicy must be set.
      policy: "none"
      # set versioning for
      # bucket [true|false]
      versioning: false
      # set objectlocking for
      # bucket [true|false] NOTE: versioning is enabled by default if you use locking
      objectlocking: false

portal:
  enabled: false
  ingress:
    enabled: false
    hosts:
      - host: localhost
  enableplayground: false
  oidc:
    enableoidc: false
    clientID: bff-client
    issuerURL: https://portal.172.22.96.167.nip.io/oidc
    clientSecret: 61324af0-1234-4f61-b110-ef57013267d6
    masterURL: https://k8s.172.22.96.167.nip.io
