apiVersion: v1
kind: Secret
metadata:
  name: zhipuai
  namespace: arcadia
type: Opaque
data:
  apiKey: "MjZlMzA4YzljNTA2NjcxNmFjYjdhM2M0OGUyZGU0YTcuck9zWktDVEJ0RzljV2JKNw==" # replace this with your API key
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Embedder
metadata:
  name: zhipuai-embedders-sample
  namespace: arcadia
spec:
  serviceType: "zhipuai"
  provider:
    endpoint:
      url: "https://open.bigmodel.cn/api/paas/v3/model-api" # replace this with your LLM URL(Zhipuai use predefined url https://open.bigmodel.cn/api/paas/v3/model-api)
      authSecret:
        kind: secret
        name: zhipuai
