apiVersion: v1
kind: Secret
metadata:
  name: gemini
  namespace: arcadia
type: Opaque
data:
  apiKey: "QUl6YVN5QVZOdGRYOHpkeU5pNWpubzNYSExUWGM0UnpJSGxIRUFz"
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Embedder
metadata:
  name: embedders-sample
  namespace: arcadia
spec:
  type: "gemini"
  provider:
    endpoint:
      url: "https://generativelanguage.googleapis.com/"
      authSecret:
        kind: secret
        name: gemini
