apiVersion: v1
kind: Secret
metadata:
  name: zhipuai
type: Opaque
data:
  apiKey: "NGZjY2VjZWIxNjY2Y2QxMTgwOGMyMThkNmQ2MTk5NTAuVENYVXZhUUNXRnlJa3hCMw==" # replace this with your API key
---
apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: LLM
metadata:
  name: zhipuai
spec:
  type: "zhipuai"
  provider:
    endpoint:
      url: "https://open.bigmodel.cn/api/paas/v3/model-api" # replace this with your LLM URL(Zhipuai use predefined url https://open.bigmodel.cn/api/paas/v3/model-api)
      authSecret:
        kind: secret
        name: zhipuai
