apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Worker
metadata:
  name: qwen-7b-chat
  namespace: arcadia
spec:
  displayName: 通义千问7B对话
  description: "这是一个对话模型服务,由通义千问提供"
  type: "fastchat"
  model:
    kind: "Models"
    name: "qwen-7b-chat"
  replicas: 1
  resources:
    limits:
      nvidia.com/gpu: "1" # request 1 GPU
