apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Dataset
metadata:
  name: dataset-playground
  namespace: arcadia
spec:
  contentType: text
  description: test dataset management
  displayName: dataset example
  field: finance
