apiVersion: arcadia.kubeagi.k8s.com.cn/v1alpha1
kind: Worker
metadata:
  name: worker-sample
  namespace: arcadia
spec:
  type: "fastchat"
  model:
    kind: "Models"
    name: "baichuan2-7b"
  resources:
    limits:
      nvidia.com/gpu: "1" # request 1 GPU
