## Append samples you want in your CSV to this file as resources ##
resources:
- arcadia_v1alpha1_laboratory.yaml
- arcadia_v1alpha1_llm.yaml
- arcadia_v1alpha1_prompt.yaml
- arcadia_v1alpha1_datasource.yaml
- arcadia_v1alpha1_embedders.yaml
- arcadia_v1alpha1_dataset.yaml
- arcadia_v1alpha1_versioneddataset.yaml
- arcadia_v1alpha1_worker.yaml
- arcadia_v1alpha1_model.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
