apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-llama-factory
  name: {{ .Release.Name }}-llama-factory
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: http
      port: 7860
      protocol: TCP
      targetPort: 7860
  selector:
    app: {{ .Release.Name }}-llama-factory
  sessionAffinity: None
  type: ClusterIP
