apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-fastchat
  labels:
    control-plane: {{ .Release.Name }}-fastchat
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.apiServer.port }}
      targetPort: {{ .Values.service.apiServer.port }}
      protocol: TCP
      name: api
    - port: {{ .Values.service.controller.port }}
      targetPort: {{ .Values.service.controller.port }}
      protocol: TCP
      name: controller
  selector:
    control-plane: {{ .Release.Name }}-fastchat